version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4173:5173
    volumes:
      - .:/app
    command: npm run serve

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posts_db
